apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: policy-controller-admission
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
