namespace: atomist
resources:
- namespace.yaml
- cert_job_cluster_role.yaml
- cert_job_role.yaml
- cert_job_service_account.yaml
- cert_job_cluster_role_binding.yaml
- cert_job_role_binding.yaml
commonLabels:
  app.kubernetes.io/name: atomist
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
