namespace: atomist
resources:
- deployment.yaml
- service.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- namespace.yaml
- pod_disruption_budget.yaml
commonLabels:
  app.kubernetes.io/name: atomist
images:
- name: vonwig/adm-ctrl
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
