namespace: atomist
secretGenerator:
- envs:
  - endpoint.env
  name: endpoint
- files:
  - server.jks
  literals:
  - password=replacethis
  name: keystore
resources:
- deployment.yaml
- service.yaml
- service_account.yaml
- cluster_role.yaml
- namespace.yaml
commonLabels:
  app.kubernetes.io/name: atomist
images:
- name: atomist/adm-ctrl
  newTag: v5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
