namespace: atomist
secretGenerator:
- envs:
  - keystore.env
  files:
  - server.pkcs12
  name: keystore
resources:
- deployment.yaml
- service.yaml
- service_account.yaml
- cluster_role.yaml
- cluster_role_binding.yaml
- namespace.yaml
commonLabels:
  app.kubernetes.io/name: atomist
images:
- name: atomist/adm-ctrl
  newTag: v2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
