apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rules.policy-controller.atomist.com
spec:
  group: policy-controller.atomist.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                query:
                  type: string
                message:
                  type: string
  scope: Namespaced
  names:
    plural: rules
    singular: rule
    kind: Rule
    shortNames:
    - rule
    # categories is a list of grouped resources the custom resource belongs to.
    categories:
    - all
