apiVersion: batch/v1
kind: Job
metadata:
  name: keystore-create
  namespace: atomist
  annotations:
    app.kubernetes.io/name: atomist
spec:
  template:
    metadata:
      name: keystore-create
      labels:
        app.kubernetes.io/name: atomist
    spec:
      containers:
        - name: keystore-create
          image: atomist/pkcs-create@sha256:907319c356f507998242f02c8195052d5d47382811c9822a8e9161a0c0285032
          imagePullPolicy: Always
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          securityContext:
            allowPrivilegeEscalation: false
      restartPolicy: OnFailure
      serviceAccountName: policy-controller-admission
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534

